# Generated by Django 2.0.7 on 2018-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_price', models.IntegerField(default=0)),
                ('book_author', models.CharField(max_length=60)),
            ],
        ),
    ]
